### ISSUE TITLE
SSL Error

### ISSUE THREAD

**Issue by bishopgodsey** [YunoHost-Apps/cloudlog_ynh#6]
Yunohost version: 11.2.3
Cloud log version: 2.4.5-ynh1
Private VPS
Login via web and ssh
Let’s Encrypt cert installed.

Install succeeds. When you go to domain you get an ERR_SSL_PROTOCOL_ERROR. 

No error logs.

**Comment by ericgaspar** [comment]
Sorry for the late reply, do you still have this issue? I can't reproduce it.

**Comment by BishopGreer** [comment]
Issue is resolved.
